---
title: "AMP phase 1 lowinput"
output:
    html_document:
        code_folding: hide
        toc: yes
        toc_float: yes
---

Notes: Only need `des_leuk` section...

```{r libraries, results='hide', echo = FALSE}
suppressPackageStartupMessages({
library(DESeq2)
library(data.table)
library(dplyr)
library(stringr)
library(ggplot2)
library(ggrepel)
library(GGally)
library(assertthat)
library(tidyverse)
library(ComplexHeatmap)
library(org.Hs.eg.db)
library(ggbeeswarm)
library(biobroom)
})
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, dev = c('png', 'pdf'), cache = TRUE, autodep = TRUE)
```

## Load AMP low input data

```{r amp_lowinput}
ll = load('private/AMP_phase1_lowInput_RA.rda')
rm(tpmt, cdt, tpm)
rowdat = data_frame(SYMBOL = mapIds(org.Hs.eg.db, keys = rownames(cd), keytype = 'ENSEMBL', column = 'SYMBOL', multiVals = 'first'),
                    ENSEMBL = rownames(cd))
meta = read_tsv('private/AMP_lowInput_masterMetadata_020617.txt')
fan_meta = readxl::read_xlsx('private/postQC_all_samples.xlsx') %>% 
    dplyr::select(Donor.ID = Patient,  DAS28_fan =  DAS28, inflam_mahalanobis = Mahalanobis) %>%
    mutate(DAS28_fan = as.numeric(DAS28_fan))

more_clinical = readr::read_csv('private/clinical_cleanup.csv') %>% rename(Donor.ID = sample) %>% filter(!duplicated(Donor.ID)) 

m$treatment = m$Cell.type
m$ncells = '~1000'
m$sizeFactor = NA_real_
m$experiment = 'AMP low input'

m = left_join(m %>% dplyr::select(Cell.type, Sample.ID), meta)
m = left_join(m, more_clinical)
m$Bcells.ov.Live = 100 * m$Bcells.ov.CD45pos*m$CD45pos.ov.Live/(100^2)
m$Tcells.ov.Live = 100 * m$Tcells.ov.CD45pos*m$CD45pos.ov.Live/(100^2)


tissue = tribble(~tissue, ~Tissue.type,
                 'RAA', 'RA-arthro',
                 'RAB', 'RA-biopsy',
                 'OAA', 'OA-arthro')
m = left_join(m, tissue) %>% left_join(fan_meta)

se = SummarizedExperiment(assays = list(counts=as.matrix(cd)), colData = m, rowData = rowdat)
assays(se)$lcpm = log2(1+t(t(assay(se))/colSums(assay(se)))*1e6)
```


## Severity/NRA4A1

```{r des_tissue}
genes2 = tibble(SYMBOL = c('NR4A1', 'NR4A2', 'NR4A3', 'ITGAX', 'TBX21', 'IGHD1', 'XBP1', 'TCL1A', 'CD69', 'CD83'))

se_b = se[,se$Cell.type == 'B cell']
#rownames(se_b) = rowData(se_b)$SYMBOL
se_b = se_b[rowSums(assay(se_b)>0)>3,]
se_b$DAS27_CRP = scale(as.numeric(se_b$Auto.calculation.of.DAS28.CRP))
se_b$DAS27_CRP = ifelse(is.na(se_b$DAS27_CRP), as.numeric(str_extract(se_b$Manual.DAS.28.CRP, '[0-9.]+$')), se_b$DAS27_CRP)
assays(se_b) = assays(se_b)['counts']
assay(se_b) = round(assay(se_b))
se_b$tissue = forcats::fct_relevel(factor(se_b$tissue), 'RAB')
des = DESeqDataSet(se_b, design = ~ tissue)
des_tissue = DESeq(des)
tissue_res = left_join(tidy(des_tissue) %>% dplyr::rename( ENSEMBL = gene), rowdat) %>% semi_join(genes2) %>% filter(term != 'Intercept')
res_plot = ggplot(tissue_res, aes(x = estimate, y = -log10(p.value), color = baseMean, label = SYMBOL)) + geom_text() + facet_wrap(~term) + theme_bw() + geom_hline(yintercept = -log10(0.05))

res_plot_uncert = res_plot + geom_errorbarh(aes(xmin = estimate - stderror*1.96, xmax = estimate + stderror*1.96))

res_plot
```

## Biopsy selected genes
```{r tissue_selected_genes, dev = c('png', 'pdf')}
library(biobroom)
library(forcats)

genes3 = tibble(SYMBOL = c('NR4A1', 'NR4A2', 'NR4A3', 'CD69', 'CD83', 'LMNA', 'GPR183', "LY9", "CXCR4"))

cleanup_res = function(deseq, term_remap_tbl){
    wl_results = left_join(tidy(deseq) %>% dplyr::rename( ENSEMBL = gene), rowdat) %>% semi_join(genes3) %>% filter(term != 'Intercept') #%>% rename(p.value = pvalue, estimate = log2FoldChange)
                                                                                                                                        
wl_results = wl_results %>% 
    mutate(gene = SYMBOL, 
           star = case_when(p.value < .01 ~ '**', p.value < .05 ~ '*', p.value<.1 ~ '^', TRUE ~  ''), 
           nestimate = -estimate,
           gene = fct_reorder(factor(gene), nestimate))
if(!missing(term_remap_tbl)){
    wl_results = left_join(term_remap_tbl, wl_results)
   
} else{
    wl_results$nterm = wl_results$term
}

wl_results
}

term_remap_tbl = tribble(~ term, ~nterm,  
                         'tissue_OAA_vs_RAB', 'RA Biopsy\nvs OA', 
                         'tissue_RAA_vs_RAB', 'RA Biopsy\nvs RA Arthroplasty')

wl_results = cleanup_res(des_tissue, term_remap_tbl)


barplot = ggplot(wl_results, aes(x = gene, y = nestimate, fill = nterm)) + geom_col(position = 'dodge') + coord_flip() + ylab('log2-fold change') + xlab('Gene') + scale_y_continuous() + geom_hline(yintercept = 0, lty = 2) + labs(caption = '**: significant at 1%; *: significant at 5%; ^: signficant at 10%') + geom_text(aes(label = star), position = position_dodge(width = .5)) + theme_bw()

barplot

```

```{r des_das}
des = DESeqDataSet(se_b[,!is.na(se_b$DAS27_CRP)], design = ~  DAS27_CRP)
des_das = DESeq(des)
das_res = left_join(tidy(des_das) %>% dplyr::rename( ENSEMBL = gene), rowdat) %>% semi_join(genes2) %>% filter(term != 'Intercept')
res_plot %+% das_res

res_plot_uncert %+% das_res
```


### Fan-resolved DAS

```{r des_dasfan}
des = DESeqDataSet(se_b[,!is.na(se_b$DAS28_fan)], design = ~  DAS28_fan)
des_das = DESeq(des)
assays(des_das)$lcpm = log2(1+t(t(assay(des_das, 'counts'))/colSums(assay(des_das, 'counts')))*1e6)

das_res = left_join(tidy(des_das) %>% dplyr::rename( ENSEMBL = gene), rowdat) %>% semi_join(genes2) %>% filter(term != 'Intercept')
res_plot %+% das_res

qplot(y = assay(des_das, 'lcpm')['ENSG00000153234',], # NR4A2
      x = des_das$DAS28_fan, geom = 'point') + ylab('NR4A2')

qplot(y = assay(des_das,  'lcpm')['ENSG00000123358',], # NR4A1
      x = des_das$DAS28_fan, geom = 'point') + ylab('NR4A1')

qplot(y = assay(des_das,  'lcpm')['ENSG00000140678',], # ITGAX
      x = des_das$DAS28_fan, geom = 'point', color = des_das$Tissue.type) + ylab('log2(ITGAX + 1) CPM')

cor.test( assay(des_das,  'lcpm')['ENSG00000140678',],  des_das$DAS28_fan)
```

### B/Live cells

```{r des_lymp}
des = DESeqDataSet(se_b[,!is.na(se_b$Bcells.ov.Live)], design = ~  Bcells.ov.Live)
des_bcell = DESeq(des)
das_bcell = left_join(tidy(des_bcell) %>% dplyr::rename( ENSEMBL = gene), rowdat) %>% semi_join(genes2) %>% filter(term != 'Intercept')
res_plot %+% das_bcell

b_results = cleanup_res(des_bcell)

```

### T/Live

```{r des_tcell}
des = DESeqDataSet(se_b[,!is.na(se_b$Tcells.ov.Live)], design = ~  Tcells.ov.Live)
des_tcell = DESeq(des)
das_tcell = left_join(tidy(des_tcell) %>% dplyr::rename( ENSEMBL = gene), rowdat) %>% semi_join(genes2) %>% filter(term != 'Intercept')
res_plot %+% das_tcell

t_results = cleanup_res(des_tcell)

```

```{r}
(barplot %+% bind_rows(b_results)) + aes(y = estimate)
```


### Duration

```{r des_duration}
des = DESeqDataSet(se_b[,!is.na(se_b$duration_yrs)], design = ~  duration_yrs)
des_duration = DESeq(des)
das_duration = left_join(tidy(des_duration) %>% dplyr::rename( ENSEMBL = gene), rowdat) %>% semi_join(genes2) %>% filter(term != 'Intercept')
res_plot %+% das_duration
res_plot_uncert %+% das_duration
duration_results = cleanup_res(des_duration)

```

### Anti-ccp

```{r des_ccp}
des = DESeqDataSet(se_b[,!is.na(se_b$anti_ccp_num)], design = ~  anti_ccp_num)
des_ccp = DESeq(des)
das_ccp = left_join(tidy(des_ccp) %>% dplyr::rename( ENSEMBL = gene), rowdat) %>% semi_join(genes2) %>% filter(term != 'Intercept')
res_plot %+% das_ccp

ccp_results = cleanup_res(des_ccp)

qplot(y = assay(des_ccp)['ENSG00000153234',], # NR4A2
      x = des_ccp$anti_ccp_category, geom = 'point') + ylab('NR4A2')
```

Higher levels of ccp mean lower levels of NR4A*


### Inflammatory  "Mahanoblis" Score

```{r des_inflam}
des = DESeqDataSet(se_b[,!is.na(se_b$inflam_mahalanobis)], design = ~  inflam_mahalanobis)
des_inflam = DESeq(des)
das_inflam = left_join(tidy(des_inflam) %>% dplyr::rename( ENSEMBL = gene), rowdat) %>% semi_join(genes2) %>% filter(term != 'Intercept')
res_plot %+% das_inflam

inflam_results = cleanup_res(des_inflam)
barplot %+% inflam_results  + aes(y = estimate)
```

### Categorical mahanoblis

```{r des_leuk}
se_b$leuk_cat = case_when(se_b$inflam_mahalanobis > 4.5 & se_b$tissue != 'OAA' ~ 'leukocyte rich RA',
                                 se_b$inflam_mahalanobis <= 4.5 & se_b$tissue != 'OAA' ~ 'leukocyte poor RA',
                                 se_b$tissue == 'OAA' ~ 'OA') %>% factor(levels = c('OA', 'leukocyte poor RA', 'leukocyte rich RA'))

des = DESeqDataSet(se_b[,!is.na(se_b$inflam_mahalanobis)], design = ~  leuk_cat)
des_leuk = DESeq(des)
das_inflam = left_join(tidy(des_leuk) %>% dplyr::rename( ENSEMBL = gene), rowdat) %>% semi_join(genes2) %>% filter(term != 'Intercept')
res_plot %+% das_inflam

leuk_remap = tribble(~ term, ~nterm,
                     'leuk_cat_leukocyte.poor.RA_vs_OA', 'Leuk. poor RA\nvs OA',
                     'leuk_cat_leukocyte.rich.RA_vs_OA', 'Leuk. rich RA\nvs OA')
leuk_results = cleanup_res(des_leuk) %>% dplyr::select(-nterm) %>% left_join(leuk_remap)
comb_results = bind_rows(filter(wl_results, nterm == 'RA Biopsy\nvs OA') %>% mutate(estimate = nestimate),
                         leuk_results)

barplot %+% comb_results  + aes(y = estimate) + scale_fill_discrete('') + ylab('log2 fold change')
```

### Check DAS

```{r}
knitr::kable(head(colData(se_b) %>% as.data.frame() %>% dplyr::select(Donor.ID, Sample.ID, tissue, Auto.calculation.of.DAS28.CRP, Manual.DAS.28.CRP, anti_ccp_num, anti_ccp_or_ccp2)))
```

## DAS/Tissue/B cells

```{r}
dat = colData(se_b) %>% as.data.frame()
plt = ggplot(dat, aes(x = Donor.ID, y = `Number.of.cells`, color = `Tissue.type`)) + geom_point()  + theme_minimal() + theme(axis.text.x = element_text(angle = 90))


plt + scale_y_log10()
plt + aes(y = DAS27_CRP)

plt + aes(y = Bcells.ov.Live)
plt + aes(y = Bcells.ov.CD45pos)

plt + aes(x = Bcells.ov.Live, y = Bcells.ov.CD45pos)

plt + aes(x = DAS27_CRP, y = Bcells.ov.CD45pos)

plt + aes(x = inflam_mahalanobis, y = Bcells.ov.Live)

ggplot(dat, aes(fill = factor(anti_ccp_num), x = tissue)) + geom_bar()
```


# Cross-type associations with NR4As

```{r setup-cross}
genes_nr4a = left_join(genes3, rowData(se) %>% as.data.frame() %>% dplyr::select(SYMBOL, ENSEMBL))
se_b2 = se[, se$Cell.type == 'B cell']
nr4a_total_score = colMeans(assay(se_b2, 'counts')[genes_nr4a$ENSEMBL,])
nr4a2 = assay(se_b2, 'counts')[filter(genes_nr4a, SYMBOL == 'NR4A2')$ENSEMBL,]
nr4a_covariates = data.frame(Donor.ID = se_b2$Donor.ID, nr4a_total_score = scale(nr4a_total_score), nr4a2 = scale(nr4a2))
```


```{r do-cross}
type_tests = map_dfr(c(Fibro = 'Fibro', Mono = 'Mono', 'T cell ' = 'T cell'), function(type){
  se_ = se[,se$Cell.type == type]
  colData(se_) = left_join(as.data.frame(colData(se_)), nr4a_covariates) %>% DataFrame()
  assays(se_) = list(counts = round(assays(se_)[['counts']]))
  se_ = se_[,!is.na(se_$nr4a2)]
  des_ = DESeqDataSet(se_, ~nr4a_total_score)
  des_ = DESeq(des_)
  results(des_, tidy = TRUE) %>% left_join(rowData(des_) %>% as.data.frame() %>% dplyr::select(SYMBOL, row = ENSEMBL)) %>% arrange(padj) %>% dplyr::rename(ENSEMBL = row)
}, .id = 'Cell.type')
```

```{r}
type_tests %>% filter(pvalue < .1) %>% arrange(padj) %>% write_csv('refined/nr4a_score_assoc.csv')
```

